port: 4466
#database info gathered when we provision database w/ dokku postgres plugin
databases:
  default:
    connector: postgres
    host: dokku-postgres-prisma-server-db
    port: 5432
    user: postgres
    password: apassword
    migrations: true
